import Head from 'next/head'
import Heading from '../components/general/Heading'
import Text from '../components/general/Text'
import Poster from '../components/general/Poster'
import Examples from '../components/general/Examples'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main>
        <Poster />
        <Heading title="О нас" />
        <Text key="1" text="Наши торты — лучшие в Хабаровске! У нас можно купить торты в Хабаровске. Наши торты порадуют великолепным и необычным внешним видом и приведут в восторг изумительным вкусом. " />
        <Text key="2" text="«ТортоМастер» поможет Вам дополнить Ваше мероприятие вкусным и оригинальным сладким произведением кулинарного искусства!" />
        <Text key="3" text="Подход к выполнению каждого заказа индивидуальный — мы всегда поможем с выбором основы, начинки, кремов и оформлением. Наш торт станет настоящим украшением Вашего торжества. Попробовав однажды наше изделие, Вы уже не сможете отказать себе в желании снова и снова насладиться этим незабываемым вкусом!" />
        <Text key="4" text="Мы любим свое дело и всегда с большой ответственностью подходим к его выполнению! Ваши пожелания — наше исполнение!" />
        <Heading title="Наши торты" />
        <Examples />
        <Heading title="Контакты" />
        <Text key="5" text="Мы ждем вас по адресу: Серышева, 82" />
        <Text key="6" text="Время работы: с 10:00 до 18:00" />
        <br />
      </main>
    </div>
  )
}
